/*
 * Webservice ArzTI API
 *
 * Kommunikation des Genossenschafts-Webservers mit den jeweiligen Rechenzentren   Bitte erst den Rezept-Status abfragen, ggf. weiter filtern und dann mit den UUID die Rezeptdaten holen.  Weitere links: - [Systembeschreibung](https://wiki.arz.software/de/Systembeschreibung/ArzTi_Verhalten_API) - [Swagger](./openapi.yaml.txt) - [History](./history.md)   Einzelne Rezepte sind Listen mit einem Element.
 *
 * The version of the OpenAPI document: 1.1.b
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using ArzTiServer.Api.Converters;

namespace ArzTiServer.Api.Models
{ 
        /// <summary>
        /// Die Dispensionsierung verschlüsselt oder unverschlüsselt.
        /// </summary>
        /// <value>Die Dispensionsierung verschlüsselt oder unverschlüsselt.</value>
        [TypeConverter(typeof(CustomEnumConverter<DataTyp>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum DataTyp
        {
            
            /// <summary>
            /// Enum EDispEncEnum for eDispEnc
            /// </summary>
            [EnumMember(Value = "eDispEnc")]
            EDispEncEnum = 1,
            
            /// <summary>
            /// Enum EDispDecEnum for eDispDec
            /// </summary>
            [EnumMember(Value = "eDispDec")]
            EDispDecEnum = 2
        }
}
