/*
 * Webservice ArzTI API
 *
 * Kommunikation des Genossenschafts-Webservers mit den jeweiligen Rechenzentren   Bitte erst den Rezept-Status abfragen, ggf. weiter filtern und dann mit den UUID die Rezeptdaten holen.  Weitere links: - [Systembeschreibung](https://wiki.arz.software/de/Systembeschreibung/ArzTi_Verhalten_API) - [Swagger](./openapi.yaml.txt) - [History](./history.md)   Einzelne Rezepte sind Listen mit einem Element.
 *
 * The version of the OpenAPI document: 1.1.b
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using ArzTiServer.Api.Converters;

namespace ArzTiServer.Api.Models
{ 
    /// <summary>
    /// Schlüssel: die Rezept ID
    /// </summary>
    [DataContract]
    public class RezeptId : IEquatable<RezeptId>
    {

        /// <summary>
        /// Gets or Sets Apoik
        /// </summary>
        [DataMember(Name="apoik", EmitDefaultValue=true)]
        public string? Apoik { get; set; }

        /// <summary>
        /// Gets or Sets Typ
        /// </summary>
        [DataMember(Name="typ", EmitDefaultValue=true)]
        public RezeptTyp Typ { get; set; }

        /// <summary>
        /// ApoTi Schlüssel: die Rezept ID
        /// </summary>
        /// <value>ApoTi Schlüssel: die Rezept ID</value>
        /// <example>160.000.002.530.097.16</example>
        [DataMember(Name="rezid", EmitDefaultValue=true)]
        public string? Rezid { get; set; }

        /// <summary>
        /// ApoTi Schlüssel: die Liefer ID
        /// </summary>
        /// <value>ApoTi Schlüssel: die Liefer ID</value>
        /// <example>4Z384R0N00J01HA9JZVY27F</example>
        [DataMember(Name="lieferid", EmitDefaultValue=true)]
        public string? Lieferid { get; set; }

        /// <summary>
        /// interner Schlüssel: die Rezept RUID
        /// </summary>
        /// <value>interner Schlüssel: die Rezept RUID</value>
        /// <example>ec070e4a-b454-48d0-83b4-37f8e2438475</example>
        [DataMember(Name="ruid", EmitDefaultValue=true)]
        public string? Ruid { get; set; }

        /// <summary>
        /// Gets or Sets Rezstatus
        /// </summary>
        [DataMember(Name="rezstatus", EmitDefaultValue=true)]
        public RezStatus Rezstatus { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RezeptId {\n");
            sb.Append("  Apoik: ").Append(Apoik).Append("\n");
            sb.Append("  Typ: ").Append(Typ).Append("\n");
            sb.Append("  Rezid: ").Append(Rezid).Append("\n");
            sb.Append("  Lieferid: ").Append(Lieferid).Append("\n");
            sb.Append("  Ruid: ").Append(Ruid).Append("\n");
            sb.Append("  Rezstatus: ").Append(Rezstatus).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((RezeptId)obj);
        }

        /// <summary>
        /// Returns true if RezeptId instances are equal
        /// </summary>
        /// <param name="other">Instance of RezeptId to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RezeptId other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Apoik == other.Apoik ||
                    Apoik is not null &&
                    Apoik.Equals(other.Apoik)
                ) && 
                (
                    Typ == other.Typ ||
                    
                    Typ.Equals(other.Typ)
                ) && 
                (
                    Rezid == other.Rezid ||
                    Rezid is not null &&
                    Rezid.Equals(other.Rezid)
                ) && 
                (
                    Lieferid == other.Lieferid ||
                    Lieferid is not null &&
                    Lieferid.Equals(other.Lieferid)
                ) && 
                (
                    Ruid == other.Ruid ||
                    Ruid is not null &&
                    Ruid.Equals(other.Ruid)
                ) && 
                (
                    Rezstatus == other.Rezstatus ||
                    
                    Rezstatus.Equals(other.Rezstatus)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Apoik is not null)
                    hashCode = hashCode * 59 + Apoik.GetHashCode();
                    
                    hashCode = hashCode * 59 + Typ.GetHashCode();
                    if (Rezid is not null)
                    hashCode = hashCode * 59 + Rezid.GetHashCode();
                    if (Lieferid is not null)
                    hashCode = hashCode * 59 + Lieferid.GetHashCode();
                    if (Ruid is not null)
                    hashCode = hashCode * 59 + Ruid.GetHashCode();
                    
                    hashCode = hashCode * 59 + Rezstatus.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(RezeptId left, RezeptId right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(RezeptId left, RezeptId right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
