/*
 * Webservice ArzTI API
 *
 * Kommunikation des Genossenschafts-Webservers mit den jeweiligen Rechenzentren   Bitte erst den Rezept-Status abfragen, ggf. weiter filtern und dann mit den UUID die Rezeptdaten holen.  Weitere links: - [Systembeschreibung](https://wiki.arz.software/de/Systembeschreibung/ArzTi_Verhalten_API) - [Swagger](./openapi.yaml.txt) - [History](./history.md)   Einzelne Rezepte sind Listen mit einem Element.
 *
 * The version of the OpenAPI document: 1.1.b
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using ArzTiServer.Api.Converters;

namespace ArzTiServer.Api.Models
{ 
    /// <summary>
    /// Schlüssel: die Rezept UUId
    /// </summary>
    [DataContract]
    public class RezeptUUId : IEquatable<RezeptUUId>
    {
        /// <summary>
        /// Gets or Sets Typ
        /// </summary>
        [Required]
        [DataMember(Name="typ", EmitDefaultValue=true)]
        public RezeptTyp Typ { get; set; }

        /// <summary>
        /// interner Schlüssel: die Rezept RUID
        /// </summary>
        /// <value>interner Schlüssel: die Rezept RUID</value>
        /// <example>8db50e3f-aa8-4452-ad32-263513ec7982</example>
        [Required]
        [DataMember(Name="ruid", EmitDefaultValue=false)]
        public string Ruid { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RezeptUUId {\n");
            sb.Append("  Typ: ").Append(Typ).Append("\n");
            sb.Append("  Ruid: ").Append(Ruid).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((RezeptUUId)obj);
        }

        /// <summary>
        /// Returns true if RezeptUUId instances are equal
        /// </summary>
        /// <param name="other">Instance of RezeptUUId to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RezeptUUId other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Typ == other.Typ ||
                    
                    Typ.Equals(other.Typ)
                ) && 
                (
                    Ruid == other.Ruid ||
                    Ruid is not null &&
                    Ruid.Equals(other.Ruid)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + Typ.GetHashCode();
                    if (Ruid is not null)
                    hashCode = hashCode * 59 + Ruid.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(RezeptUUId left, RezeptUUId right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(RezeptUUId left, RezeptUUId right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
