/*
 * Webservice ArzTI API
 *
 * Kommunikation des Genossenschafts-Webservers mit den jeweiligen Rechenzentren   Bitte erst den Rezept-Status abfragen, ggf. weiter filtern und dann mit den UUID die Rezeptdaten holen.  Weitere links: - [Systembeschreibung](https://wiki.arz.software/de/Systembeschreibung/ArzTi_Verhalten_API) - [Swagger](./openapi.yaml.txt) - [History](./history.md)   Einzelne Rezepte sind Listen mit einem Element.
 *
 * The version of the OpenAPI document: 1.1.b
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using ArzTiServer.Api.Converters;

namespace ArzTiServer.Api.Models
{ 
        /// <summary>
        /// Verarbeitungs-Status des Rezepts
        /// </summary>
        /// <value>Verarbeitungs-Status des Rezepts</value>
        [TypeConverter(typeof(CustomEnumConverter<RezStatus>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum RezStatus
        {
            
            /// <summary>
            /// Enum VORPRUEFUNGEnum for VOR_PRUEFUNG
            /// </summary>
            [EnumMember(Value = "VOR_PRUEFUNG")]
            VORPRUEFUNGEnum = 1,
            
            /// <summary>
            /// Enum VORABRECHNUNGEnum for VOR_ABRECHNUNG
            /// </summary>
            [EnumMember(Value = "VOR_ABRECHNUNG")]
            VORABRECHNUNGEnum = 2,
            
            /// <summary>
            /// Enum FEHLEREnum for FEHLER
            /// </summary>
            [EnumMember(Value = "FEHLER")]
            FEHLEREnum = 3,
            
            /// <summary>
            /// Enum VERBESSERBAREnum for VERBESSERBAR
            /// </summary>
            [EnumMember(Value = "VERBESSERBAR")]
            VERBESSERBAREnum = 4,
            
            /// <summary>
            /// Enum RUECKWEISUNGEnum for RUECKWEISUNG
            /// </summary>
            [EnumMember(Value = "RUECKWEISUNG")]
            RUECKWEISUNGEnum = 5,
            
            /// <summary>
            /// Enum ABGERECHNETEnum for ABGERECHNET
            /// </summary>
            [EnumMember(Value = "ABGERECHNET")]
            ABGERECHNETEnum = 6,
            
            /// <summary>
            /// Enum STORNIERTEnum for STORNIERT
            /// </summary>
            [EnumMember(Value = "STORNIERT")]
            STORNIERTEnum = 7,
            
            /// <summary>
            /// Enum HINWEISEnum for HINWEIS
            /// </summary>
            [EnumMember(Value = "HINWEIS")]
            HINWEISEnum = 8,
            
            /// <summary>
            /// Enum ABRECHENBAREnum for ABRECHENBAR
            /// </summary>
            [EnumMember(Value = "ABRECHENBAR")]
            ABRECHENBAREnum = 9
        }
}
