/*
 * Webservice ArzTI API
 *
 * Kommunikation des Genossenschafts-Webservers mit den jeweiligen Rechenzentren   Bitte erst den Rezept-Status abfragen, ggf. weiter filtern und dann mit den UUID die Rezeptdaten holen.  Weitere links: - [Systembeschreibung](https://wiki.arz.software/de/Systembeschreibung/ArzTi_Verhalten_API) - [Swagger](./openapi.yaml.txt) - [History](./history.md)   Einzelne Rezepte sind Listen mit einem Element.
 *
 * The version of the OpenAPI document: 1.1.b
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using ArzTiServer.Api.Converters;

namespace ArzTiServer.Api.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public class Statusinfo : IEquatable<Statusinfo>
    {
        /// <summary>
        /// Rezeptstatus
        /// </summary>
        /// <value>Rezeptstatus</value>
        /// <example>FEHLER</example>
        [DataMember(Name="status", EmitDefaultValue=false)]
        public string? Status { get; set; }

        /// <summary>
        /// Gets or Sets Fcode
        /// </summary>
        /// <example>14</example>
        [DataMember(Name="fcode", EmitDefaultValue=true)]
        public string? Fcode { get; set; }

        /// <summary>
        /// Gets or Sets Fstatus
        /// </summary>
        /// <example>FEHLER</example>
        [DataMember(Name="fstatus", EmitDefaultValue=true)]
        public string? Fstatus { get; set; }

        /// <summary>
        /// Gets or Sets Fkommentar
        /// </summary>
        /// <example>Kein Kommentar.</example>
        [DataMember(Name="fkommentar", EmitDefaultValue=true)]
        public string? Fkommentar { get; set; }

        /// <summary>
        /// Gets or Sets Ftcode
        /// </summary>
        /// <example>2</example>
        [DataMember(Name="ftcode", EmitDefaultValue=true)]
        public string? Ftcode { get; set; }

        /// <summary>
        /// Gets or Sets Posnr
        /// </summary>
        /// <example>1</example>
        [DataMember(Name="posnr", EmitDefaultValue=true)]
        public int? Posnr { get; set; }

        /// <summary>
        /// Gets or Sets Fkurztext
        /// </summary>
        /// <example>Da stimmt was nicht!</example>
        [DataMember(Name="fkurztext", EmitDefaultValue=true)]
        public string? Fkurztext { get; set; }

        /// <summary>
        /// Gets or Sets Fhauptfehler
        /// </summary>
        /// <example>true</example>
        [DataMember(Name="fhauptfehler", EmitDefaultValue=true)]
        public bool? Fhauptfehler { get; set; } = false;

        /// <summary>
        /// Gets or Sets Error
        /// </summary>
        [DataMember(Name="error", EmitDefaultValue=false)]
        public Error? Error { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Statusinfo {\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Fcode: ").Append(Fcode).Append("\n");
            sb.Append("  Fstatus: ").Append(Fstatus).Append("\n");
            sb.Append("  Fkommentar: ").Append(Fkommentar).Append("\n");
            sb.Append("  Ftcode: ").Append(Ftcode).Append("\n");
            sb.Append("  Posnr: ").Append(Posnr).Append("\n");
            sb.Append("  Fkurztext: ").Append(Fkurztext).Append("\n");
            sb.Append("  Fhauptfehler: ").Append(Fhauptfehler).Append("\n");
            sb.Append("  Error: ").Append(Error).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Statusinfo)obj);
        }

        /// <summary>
        /// Returns true if Statusinfo instances are equal
        /// </summary>
        /// <param name="other">Instance of Statusinfo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Statusinfo other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Status == other.Status ||
                    Status is not null &&
                    Status.Equals(other.Status)
                ) && 
                (
                    Fcode == other.Fcode ||
                    Fcode is not null &&
                    Fcode.Equals(other.Fcode)
                ) && 
                (
                    Fstatus == other.Fstatus ||
                    Fstatus is not null &&
                    Fstatus.Equals(other.Fstatus)
                ) && 
                (
                    Fkommentar == other.Fkommentar ||
                    Fkommentar is not null &&
                    Fkommentar.Equals(other.Fkommentar)
                ) && 
                (
                    Ftcode == other.Ftcode ||
                    Ftcode is not null &&
                    Ftcode.Equals(other.Ftcode)
                ) && 
                (
                    Posnr == other.Posnr ||
                    
                    Posnr.Equals(other.Posnr)
                ) && 
                (
                    Fkurztext == other.Fkurztext ||
                    Fkurztext is not null &&
                    Fkurztext.Equals(other.Fkurztext)
                ) && 
                (
                    Fhauptfehler == other.Fhauptfehler ||
                    Fhauptfehler is not null &&
                    Fhauptfehler.Equals(other.Fhauptfehler)
                ) && 
                (
                    Error == other.Error ||
                    Error is not null &&
                    Error.Equals(other.Error)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Status is not null)
                    hashCode = hashCode * 59 + Status.GetHashCode();
                    if (Fcode is not null)
                    hashCode = hashCode * 59 + Fcode.GetHashCode();
                    if (Fstatus is not null)
                    hashCode = hashCode * 59 + Fstatus.GetHashCode();
                    if (Fkommentar is not null)
                    hashCode = hashCode * 59 + Fkommentar.GetHashCode();
                    if (Ftcode is not null)
                    hashCode = hashCode * 59 + Ftcode.GetHashCode();
                    
                    hashCode = hashCode * 59 + Posnr.GetHashCode();
                    if (Fkurztext is not null)
                    hashCode = hashCode * 59 + Fkurztext.GetHashCode();
                    if (Fhauptfehler is not null)
                    hashCode = hashCode * 59 + Fhauptfehler.GetHashCode();
                    if (Error is not null)
                    hashCode = hashCode * 59 + Error.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(Statusinfo left, Statusinfo right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Statusinfo left, Statusinfo right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
