/*
 * Webservice ArzTI API
 *
 * Kommunikation des Genossenschafts-Webservers mit den jeweiligen Rechenzentren   Bitte erst den Rezept-Status abfragen, ggf. weiter filtern und dann mit den UUID die Rezeptdaten holen.  Weitere links: - [Systembeschreibung](https://wiki.arz.software/de/Systembeschreibung/ArzTi_Verhalten_API) - [Swagger](./openapi.yaml.txt) - [History](./history.md)   Einzelne Rezepte sind Listen mit einem Element.
 *
 * The version of the OpenAPI document: 1.1.b
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using ArzTiServer.Api.Attributes;
using ArzTiServer.Api.Models;

namespace ArzTiServer.Api.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public abstract class RezeptPruefApiController : ControllerBase
    { 
        /// <summary>
        /// Überträgt  eine Liste von Rezepten zur Prüfung
        /// </summary>
        /// <remarks>postQueryPruefRequest</remarks>
        /// <param name="rezeptId">user to add to the system</param>
        /// <response code="202">die Liste wurde akzeptiert</response>
        /// <response code="401">Unauthorized</response>
        /// <response code="404">The specified resource was not found</response>
        /// <response code="413">Unauthorized</response>
        [HttpPost]
        [Route("/v1/rezept/pruefrequest")]
        [Consumes("application/json")]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 401, type: typeof(Error))]
        [ProducesResponseType(statusCode: 404, type: typeof(Error))]
        [ProducesResponseType(statusCode: 413, type: typeof(Error))]
        public abstract Task<IActionResult> PostQueryPruefeRezepte([FromBody]List<RezeptId> rezeptId);

        /// <summary>
        /// ermittelt das Prüfergebnis für die übermittelten RezeptUIDs
        /// </summary>
        /// <remarks>postQueryPruefResult</remarks>
        /// <param name="rezeptId"></param>
        /// <response code="200">Liefert eine Liste der Status aller Rezepte</response>
        /// <response code="401">Unauthorized</response>
        /// <response code="404">The specified resource was not found</response>
        /// <response code="413">Unauthorized</response>
        [HttpPost]
        [Route("/v1/rezept/pruefresult")]
        [Consumes("application/json")]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 200, type: typeof(List<RezeptPruefResult>))]
        [ProducesResponseType(statusCode: 401, type: typeof(Error))]
        [ProducesResponseType(statusCode: 404, type: typeof(Error))]
        [ProducesResponseType(statusCode: 413, type: typeof(Error))]
        public abstract Task<IActionResult> PostQueryPruefeRezepteResult([FromBody]List<RezeptId> rezeptId);
    }
}
