#!/usr/bin/env bash
#
# Generated by: https://openapi-generator.tech
#

dotnet restore src/ArzTiServer.Api/ && \
    dotnet build src/ArzTiServer.Api/ && \
    echo "Now, run the following to start the project: dotnet run -p src/ArzTiServer.Api/ArzTiServer.Api.csproj --launch-profile web"
